"""Rendering the PAC file and serving exactly that one file."""
from __future__ import annotations

import json
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

from . import paths

PAC_CONTENT_TYPE = "application/x-ns-proxy-autoconfig"
PAC_ROUTE = "/proxy.pac"

_TEMPLATE = """\
// Generated by subbox. Edit pac.domains in config.toml and run `subbox pac`.
function FindProxyForURL(url, host) {{
    var PROXY = "PROXY {addr}:{port}; SOCKS5 {addr}:{port}; DIRECT";
    var proxied = {domains};

    for (var i = 0; i < proxied.length; i++) {{
        var d = proxied[i];
        if (host === d || dnsDomainIs(host, "." + d)) {{
            return PROXY;
        }}
    }}
    return "DIRECT";
}}
"""


def _js_array(domains: list[str]) -> str:
    """Render the domain list as an indented JavaScript array literal.

    json.dumps gives correct string escaping for free, which matters
    because the domain list is user input.
    """
    if not domains:
        return "[]"
    items = ",\n".join(f"        {json.dumps(d)}" for d in sorted(domains))
    return "[\n" + items + "\n    ]"


def render(domains: list[str], listen_addr: str, listen_port: int) -> str:
    return _TEMPLATE.format(
        addr=listen_addr,
        port=listen_port,
        domains=_js_array(domains),
    )


def write(cfg: dict) -> Path:
    out = paths.pac_file()
    out.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    out.write_text(render(
        cfg["pac"]["domains"],
        cfg["proxy"]["listen_addr"],
        cfg["proxy"]["listen_port"],
    ))
    out.chmod(0o644)
    return out


class Handler(BaseHTTPRequestHandler):
    """Serves one file at one route. Everything else is a 404."""

    server_version = "subbox-pac"

    def do_GET(self) -> None:  # noqa: N802 — name fixed by the base class
        if self.path != PAC_ROUTE:
            self.send_error(404, "not found")
            return
        try:
            body = paths.pac_file().read_bytes()
        except OSError:
            self.send_error(503, "PAC file not generated yet")
            return
        self.send_response(200)
        self.send_header("Content-Type", PAC_CONTENT_TYPE)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt: str, *args) -> None:
        pass  # the journal does not need a line per browser PAC refresh


def serve(cfg: dict) -> None:
    httpd = HTTPServer(("127.0.0.1", cfg["pac"]["port"]), Handler)
    httpd.serve_forever()
